name: Frontend CI

on:
  push:
    paths:
      - 'greentrack-frontend/**'
  pull_request:
    paths:
      - 'greentrack-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./greentrack-frontend

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'
        cache: 'npm'
        cache-dependency-path: greentrack-frontend/package-lock.json

    - name: Instalar dependencias
      run: npm ci

    - name: Construir Aplicaci√≥n Angular
      run: npm run build -- --configuration production